name: firebase_complete_demo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.2
  page_transition: ^2.1.0
  another_flushbar: ^1.12.30
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  double_back_to_close_app: ^2.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  flutter_dotenv: ^5.1.0
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  firebase_remote_config: ^5.0.3
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/logos/
    - assets/fonts/poppins/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
